version: '3'
services:
  web:
    build: .
    ports:
     - "80:80"
    volumes:
     - .:/usr/src
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

volumes:
  postgres:
